### ISSUE TITLE
README.md example incorrect?

### ISSUE THREAD

**Issue by butchmarshall** [tmilos/scim-filter-parser#4]
I'm just testing out this library and finding that the first example under **Path mode**

```
$parser = new Parser(Mode::FILTER());
$node = $parser->parse('members[value eq "2819c223-7f76-453a-919d-413861904646"].displayName');
```

Throws an error

`ScimFilterParser\Error\FilterException: [Syntax Error] line 0, col 56: Error: Expected end of input, got '.'`

I assume this is just because `Parser(Mode::FILTER());` needs to be `new Parser(Mode::PATH());` ?

**Comment by tmilos** [comment]
The expression `members[value eq "2819c223-7f76-453a-919d-413861904646"].displayName` is not a valid boolean expression and does not satisfies the filter grammar defined in https://tools.ietf.org/html/rfc7644#section-3.4.2.2

It's rather a path selector that satisfies grammar defined in https://tools.ietf.org/html/rfc7644#section-3.5.2

So, the `Mode::FILTER()` is for filter grammar https://tools.ietf.org/html/rfc7644#section-3.4.2.2
And `Mode::PATH()` is for path grammar https://tools.ietf.org/html/rfc7644#section-3.5.2

**Comment by butchmarshall** [comment]
Awesome - so the README.md example is wrong then, thanks!

**Comment by tmilos** [comment]
Yes, have corrected it now. Thanks
